-- AlterTable
ALTER TABLE "sync_runs" ADD COLUMN "stage" TEXT NOT NULL DEFAULT 'DISCOVERING';
ALTER TABLE "sync_runs" ADD COLUMN "stage_done" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "sync_runs" ADD COLUMN "stage_total" INTEGER NOT NULL DEFAULT 0;
